### ISSUE TITLE
Unreturned promise

### ISSUE THREAD

**Issue by martijn-benjamin** [martijn-benjamin/filtr-api#16]
It looks like there is a bug in rethinkdash using bluebird. Following warning shows up a lot in the logs:
```
(node:47448) Warning: a promise was created in a handler at /Users/cloud-coders/Projects/filtr/filtr-api/node_modules/express/lib/router/layer.js:95:5 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/Users/cloud-coders/Projects/filtr/filtr-api/node_modules/rethinkdbdash/node_modules/bluebird/js/release/promise.js:77:14)
```

It basically means promises are not returned, left unattended. It's a warning but i feel like this could be the cause of leaking memory. We will have to check if this bug is already listed with rethinkdash / bluebird, otherwise maybe supply a PR for this.

**Comment by martijn-benjamin** [comment]
Looks like this has got something to do with users that are signed in. Maybe the passport auth checks need to be yielded as well rather than chaining the response as we do now.

this

```
r.table('users').filter({

            'facebookId': profile.id

        }).run().then(function (result) {
.......

```

should be this?

```

 var result = yield r.table('users').filter({'facebookId': profile.id}).run()

```

Not sure, have to test this.
